---
networks:
  sensor-monitor:
    external: false

services:
  sensor-monitor:
    container_name: sensor-monitor
    privileged: true # needed for /proc/device-tree/model (gpio device platform detection)
    build:
        dockerfile: ./Dockerfile
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - BOARDNAME=EnviroPlus
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
      - "/dev/spidev0.0:/dev/spidev0.1"
      - "/dev/mem:/dev/mem"
      - "/dev/gpiomem:/dev/gpiomem"
    ports:
      - 8080:8080
    restart: unless-stopped
